-- ALL-IN-ONE.sql - every migration, in order, for a BRAND-NEW project.
--
-- GENERATED by scripts/build-combined-migration.py. Do not edit this file: edit the
-- migration it came from and regenerate, or the two drift apart.
--
-- Use it when setting a project up by hand: Dashboard -> SQL Editor -> paste -> Run,
-- once. It is NOT idempotent (`create policy` fails if the policy already exists), so
-- on a project that has already had some of these applied, run the individual files
-- and skip the ones that are done.
--
-- Files included, in this order:
--   * 0001_init.sql
--   * 0002_rls.sql
--   * 0003_functions.sql
--   * 0004_event_shares.sql
--   * 0005_event_members.sql

-- ==========================================================================
-- 0001_init.sql
-- ==========================================================================

-- 0001_init.sql — phase 2a schema: the tables an optional account syncs.
--
-- Shapes mirror lib/store/* so lib/sync/rows.ts is a field-for-field mapping and
-- nothing has to be invented at sync time.
--
-- Three rules this file encodes:
--   1. Ids are client-generated UUIDs, so a row created offline has a stable
--      identity and every push is an idempotent upsert on the primary key. The
--      pre-account local id (time+random, not a UUID) is kept in `client_id`
--      and is unique per user, so the first upload can map without duplicating.
--   2. `updated_at` is set by a trigger, never by the client. A device with a
--      wrong clock must not be able to win a conflict by lying about the time.
--   3. `user_id` is forced to auth.uid() by a trigger on insert AND update, so a
--      client cannot create a row it does not own, or hand one to someone else.
--      Row-level security (0002) is the fence; these triggers are the belt.
--
-- Soft delete: a delete sets `deleted_at` so the tombstone can reach another
-- device. The local store purges the row once it applies one.

-- ─────────────────────────────── helpers ───────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Server owns the clock for sync ordering. Never trust a client timestamp.';

create or replace function public.force_owner()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.user_id := auth.uid();
  return new;
end;
$$;

comment on function public.force_owner() is
  'Ownership is assigned, not submitted. Runs on insert and update so a row cannot be transferred.';

-- ─────────────────────────────── profiles ───────────────────────────────
-- Deliberately does NOT copy the email: auth.users already holds it, and one
-- copy is one place to delete.

create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) <= 60),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

-- ──────────────────────────────── decks ────────────────────────────────

create table if not exists public.decks (
  id          uuid primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  client_id   text check (char_length(client_id) <= 64),
  name        text not null check (char_length(name) between 1 and 80),
  description text check (char_length(description) <= 300),
  cards       jsonb not null default '[]'::jsonb
                check (jsonb_typeof(cards) = 'array' and pg_column_size(cards) <= 200000),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz,
  unique (user_id, client_id)
);

create trigger decks_owner before insert or update on public.decks
  for each row execute function public.force_owner();
create trigger decks_updated_at before update on public.decks
  for each row execute function public.set_updated_at();
create index if not exists decks_pull_idx on public.decks (user_id, updated_at);

-- ─────────────────────────────── matches ───────────────────────────────

create table if not exists public.matches (
  id          uuid primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  client_id   text check (char_length(client_id) <= 64),
  mode        text not null check (char_length(mode) <= 40),
  team1_name  text not null default '' check (char_length(team1_name) <= 80),
  team2_name  text not null default '' check (char_length(team2_name) <= 80),
  score_team1 integer not null default 0 check (score_team1 between 0 and 999),
  score_team2 integer not null default 0 check (score_team2 between 0 and 999),
  winner      smallint check (winner in (1, 2)),
  game_number integer not null default 1 check (game_number between 1 and 99),
  duration_ms bigint not null default 0 check (duration_ms >= 0),
  results     jsonb not null default '[]'::jsonb
                check (jsonb_typeof(results) = 'array' and pg_column_size(results) <= 20000),
  official    boolean not null default false,
  event_label text check (char_length(event_label) <= 120),
  game_type   text check (game_type in ('singles', 'doubles', 'mixed-doubles')),
  timeouts    jsonb,
  faults      jsonb,
  played_at   timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  deleted_at  timestamptz,
  unique (user_id, client_id)
);

create trigger matches_owner before insert or update on public.matches
  for each row execute function public.force_owner();
create trigger matches_updated_at before update on public.matches
  for each row execute function public.set_updated_at();
create index if not exists matches_pull_idx on public.matches (user_id, updated_at);

-- ───────────────────────────── tournaments ─────────────────────────────
-- The event header. Its matches are rows in their own table, not a blob inside
-- this one, because phase 2c needs two people writing different matches of one
-- event without clobbering each other.

create table if not exists public.tournaments (
  id           uuid primary key,
  user_id      uuid not null references auth.users (id) on delete cascade,
  client_id    text check (char_length(client_id) <= 64),
  name         text not null check (char_length(name) between 1 and 120),
  format       text not null check (format in
                 ('round-robin', 'single-elim', 'double-elim', 'pools-bracket', 'rotating')),
  entry_mode   text not null default 'teams' check (entry_mode in ('teams', 'rotating')),
  team_size    smallint not null default 2 check (team_size in (1, 2)),
  status       text not null default 'setup' check (status in ('setup', 'running', 'complete')),
  champion_team_id text check (char_length(champion_team_id) <= 64),
  config       jsonb not null default '{}'::jsonb
                 check (jsonb_typeof(config) = 'object' and pg_column_size(config) <= 20000),
  players      jsonb not null default '[]'::jsonb
                 check (jsonb_typeof(players) = 'array' and pg_column_size(players) <= 200000),
  teams        jsonb not null default '[]'::jsonb
                 check (jsonb_typeof(teams) = 'array' and pg_column_size(teams) <= 200000),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  unique (user_id, client_id)
);

create trigger tournaments_owner before insert or update on public.tournaments
  for each row execute function public.force_owner();
create trigger tournaments_updated_at before update on public.tournaments
  for each row execute function public.set_updated_at();
create index if not exists tournaments_pull_idx on public.tournaments (user_id, updated_at);

-- ────────────────────────── tournament_matches ─────────────────────────
-- `user_id` is denormalised from the parent event. Both are checked in the RLS
-- policy: the row must be yours AND its event must be yours, so a forged
-- tournament_id cannot attach a match to someone else's draw.

create table if not exists public.tournament_matches (
  id            uuid primary key,
  tournament_id uuid not null references public.tournaments (id) on delete cascade,
  user_id       uuid not null references auth.users (id) on delete cascade,
  client_id     text check (char_length(client_id) <= 64),
  bracket       text not null check (bracket in ('rr', 'pool', 'winners', 'losers', 'final')),
  round         integer not null default 1 check (round between 1 and 999),
  pool          text check (char_length(pool) <= 8),
  slot_a        jsonb not null default '{}'::jsonb check (jsonb_typeof(slot_a) = 'object'),
  slot_b        jsonb not null default '{}'::jsonb check (jsonb_typeof(slot_b) = 'object'),
  team_a        text check (char_length(team_a) <= 64),
  team_b        text check (char_length(team_b) <= 64),
  score_a       integer check (score_a between 0 and 999),
  score_b       integer check (score_b between 0 and 999),
  winner        text check (char_length(winner) <= 64),
  court         integer check (court between 1 and 64),
  label         text check (char_length(label) <= 40),
  played_in_app boolean not null default false,
  completed_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  unique (tournament_id, client_id)
);

create trigger tournament_matches_owner before insert or update on public.tournament_matches
  for each row execute function public.force_owner();
create trigger tournament_matches_updated_at before update on public.tournament_matches
  for each row execute function public.set_updated_at();
create index if not exists tournament_matches_event_idx
  on public.tournament_matches (tournament_id, round);
create index if not exists tournament_matches_pull_idx
  on public.tournament_matches (user_id, updated_at);

-- ─────────────────────────────── event_log ─────────────────────────────
-- The audit trail: every result, correction and clear. Append-only by design -
-- 0002 gives it no update and no delete policy at all. An audit trail somebody
-- can quietly rewrite is not an audit trail.

create table if not exists public.event_log (
  id             uuid primary key,
  tournament_id  uuid not null references public.tournaments (id) on delete cascade,
  actor_user_id  uuid not null references auth.users (id) on delete cascade,
  kind           text not null check (kind in ('created', 'result', 'edit', 'undo', 'round', 'note')),
  match_id       uuid,
  text           text not null check (char_length(text) <= 500),
  at             timestamptz not null default now(),
  created_at     timestamptz not null default now()
);

create index if not exists event_log_event_idx on public.event_log (tournament_id, at);

-- ──────────────────────────────── prefs ───────────────────────────────
-- Favorites, achievement counters and settings. One small row per user: never
-- collaborative, so there is nothing to gain from splitting it into columns.

create table if not exists public.prefs (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  data       jsonb not null default '{}'::jsonb
               check (jsonb_typeof(data) = 'object' and pg_column_size(data) <= 100000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger prefs_updated_at before update on public.prefs
  for each row execute function public.set_updated_at();

create trigger prefs_owner before insert or update on public.prefs
  for each row execute function public.force_owner();

-- event_log names its owner `actor_user_id`, so it needs its own forcing
-- trigger. Insert only: an append-only table is never updated.
create or replace function public.force_actor()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.actor_user_id := auth.uid();
  return new;
end;
$$;

create trigger event_log_actor before insert on public.event_log
  for each row execute function public.force_actor();

-- ==========================================================================
-- 0002_rls.sql
-- ==========================================================================

-- 0002_rls.sql — row-level security. This file IS the security model.
--
-- The app talks to Postgres directly from the browser with a publishable key, so
-- there is no server-side code deciding who may read what. These policies are
-- the only thing standing between two accounts, which is why:
--
--   * every table has RLS enabled, and a policy per operation (no blanket
--     `for all` - an explicit insert `with check` is what stops a client writing
--     a row it does not own);
--   * policies are scoped `to authenticated`, and `anon` is revoked outright,
--     so the unauthenticated key cannot read a single row;
--   * event_log gets SELECT and INSERT and nothing else. No update policy and no
--     delete policy means an audit trail cannot be rewritten, by anyone, ever;
--   * child rows are checked through their parent as well as their own owner
--     column, so a forged tournament_id cannot attach a match to another
--     person's event.
--
-- Verified by supabase/tests/rls.test.mjs, which tries each of these as a second
-- user and must fail. Run it after any change here.

-- ───────────────────────── revoke the anon surface ─────────────────────────
-- Supabase grants `anon` and `authenticated` table privileges by default. RLS
-- would filter anon to nothing anyway; revoking is the second lock, and it makes
-- the intent explicit to the next reader.

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;

-- ...and grant `authenticated` exactly what the app needs, explicitly. Supabase's
-- default privileges would grant this anyway; spelling it out means the migration
-- is self-contained, works on a plain Postgres (see tests/local-shim.sql), and
-- does not silently depend on a dashboard default that could change.

grant select, insert, update, delete on
  public.decks, public.matches, public.tournaments,
  public.tournament_matches, public.prefs
  to authenticated;

-- Append-only, at the privilege level as well as in policy. The revoke is not
-- redundant: Supabase's default privileges (and the local shim's) grant ALL on
-- new tables to `authenticated`, so without this line an UPDATE reaches the
-- policy layer and is stopped only by the absence of a policy. Verified - the
-- local suite reported "0 refused at privilege level" until this was added.
grant select, insert on public.event_log to authenticated;
revoke update, delete, truncate on public.event_log from authenticated;

-- A profile is created by the signup trigger, so no insert here.
grant select, update on public.profiles to authenticated;

alter table public.profiles            enable row level security;
alter table public.decks               enable row level security;
alter table public.matches             enable row level security;
alter table public.tournaments         enable row level security;
alter table public.tournament_matches  enable row level security;
alter table public.event_log           enable row level security;
alter table public.prefs               enable row level security;

-- NOT using `force row level security`, deliberately, and this is worth knowing:
-- FORCE subjects the table OWNER to the policies too. Every policy here is scoped
-- `to authenticated`, and the owner is `postgres` - so with FORCE on, the signup
-- trigger could not insert a profile and `delete_my_account()` would delete zero
-- rows while reporting success. Owner bypass is exactly what those two functions
-- need; the accounts are separated from each other by the policies below, which
-- apply to every client role.

-- ──────────────────────────────── profiles ────────────────────────────────
-- No insert policy: a profile is created by the signup trigger, not by a client.

create policy "profiles: read own" on public.profiles
  for select to authenticated using (id = (select auth.uid()));
create policy "profiles: update own" on public.profiles
  for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));

-- ───────────────────────────────── decks ─────────────────────────────────

create policy "decks: read own" on public.decks
  for select to authenticated using (user_id = (select auth.uid()));
create policy "decks: insert own" on public.decks
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "decks: update own" on public.decks
  for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "decks: delete own" on public.decks
  for delete to authenticated using (user_id = (select auth.uid()));

-- ──────────────────────────────── matches ────────────────────────────────

create policy "matches: read own" on public.matches
  for select to authenticated using (user_id = (select auth.uid()));
create policy "matches: insert own" on public.matches
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "matches: update own" on public.matches
  for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "matches: delete own" on public.matches
  for delete to authenticated using (user_id = (select auth.uid()));

-- ────────────────────────────── tournaments ──────────────────────────────

create policy "tournaments: read own" on public.tournaments
  for select to authenticated using (user_id = (select auth.uid()));
create policy "tournaments: insert own" on public.tournaments
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "tournaments: update own" on public.tournaments
  for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "tournaments: delete own" on public.tournaments
  for delete to authenticated using (user_id = (select auth.uid()));

-- ────────────────────────── tournament_matches ───────────────────────────
-- Own the row AND own its event. The parent check is what a forged
-- tournament_id runs into.

create policy "event matches: read own" on public.tournament_matches
  for select to authenticated using (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  );
create policy "event matches: insert own" on public.tournament_matches
  for insert to authenticated with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  );
create policy "event matches: update own" on public.tournament_matches
  for update to authenticated using (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  ) with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  );
create policy "event matches: delete own" on public.tournament_matches
  for delete to authenticated using (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  );

-- ──────────────────────────────── event_log ──────────────────────────────
-- SELECT and INSERT only. The absence of an update and a delete policy is the
-- feature: with RLS enabled, no policy means no permission. Correcting a score
-- appends a new line saying what it used to be; it never edits a line.

create policy "event log: read own events" on public.event_log
  for select to authenticated using (
    exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  );
create policy "event log: append to own events" on public.event_log
  for insert to authenticated with check (
    actor_user_id = (select auth.uid())
    and exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  );

-- ────────────────────────────────── prefs ────────────────────────────────

create policy "prefs: read own" on public.prefs
  for select to authenticated using (user_id = (select auth.uid()));
create policy "prefs: insert own" on public.prefs
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "prefs: update own" on public.prefs
  for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "prefs: delete own" on public.prefs
  for delete to authenticated using (user_id = (select auth.uid()));

-- ==========================================================================
-- 0003_functions.sql
-- ==========================================================================

-- 0003_functions.sql — the only privileged code in the system.
--
-- Two functions, both `security definer`, because both must do something the
-- caller's own permissions cannot: create a profile row for a brand-new user,
-- and delete an account including its `auth.users` record.
--
-- Every definer function here follows the same three rules, and they are not
-- optional:
--   1. `set search_path = ''` and every identifier schema-qualified. Without it,
--      a caller who can create objects can shadow a table name and have the
--      function operate on theirs instead - the classic Postgres definer
--      escalation.
--   2. Execute is revoked from `public` and `anon`, then granted only to
--      `authenticated`. A definer function granted to public is an open door.
--   3. It derives the account from `auth.uid()` and never takes a user id as an
--      argument. A function that deletes "the user you name" is a function that
--      deletes anybody.

-- ─────────────────── a profile row for a new signup ───────────────────
-- Runs as the trigger owner so it can insert before the user has a session.
-- Copies a display name only if the identity provider gave one - no email is
-- copied, because auth.users already holds it and one copy is one place to
-- delete.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    nullif(left(coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      ''
    ), 60), '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ───────────────────────── delete my account ─────────────────────────
-- The whole promise of "delete my account" in one transaction. Deleting the
-- auth.users row would cascade all of these anyway; they are listed explicitly
-- so that the intent is reviewable and so a future table added WITHOUT an
-- `on delete cascade` still gets removed here.
--
-- No arguments on purpose - see rule 3 above.

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'delete_my_account: no authenticated user';
  end if;

  delete from public.event_log          where actor_user_id = uid;
  delete from public.tournament_matches where user_id = uid;
  delete from public.tournaments        where user_id = uid;
  delete from public.matches            where user_id = uid;
  delete from public.decks              where user_id = uid;
  delete from public.prefs              where user_id = uid;
  delete from public.profiles           where id = uid;

  -- Last, because it cascades: after this the session's JWT refers to nobody.
  delete from auth.users where id = uid;
end;
$$;

revoke all on function public.handle_new_user() from public, anon;
revoke all on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;

comment on function public.delete_my_account() is
  'Deletes the CALLING user and every row they own. Takes no arguments by design.';

-- ==========================================================================
-- 0004_event_shares.sql
-- ==========================================================================

-- 0004_event_shares.sql — phase 2b: a read-only link to one event.
--
-- The problem this file solves: a spectator is NOT authenticated, so `auth.uid()` is
-- null and no row-level policy can say "this anonymous person may read exactly this
-- event". Granting `anon` table access would grant it to the whole internet.
--
-- So the viewer never touches a table. ONE definer function is the entire anonymous
-- surface, authorised by a token rather than by a session:
--
--     get_shared_event(p_token) -> jsonb
--
-- Everything else here exists to make that safe:
--   * only the SHA-256 HASH of a token is stored, so a database dump yields no
--     working links. Hashing happens in here, not in the browser, because
--     `crypto.subtle` is unavailable in a plain-http LAN dev session;
--   * the payload is hand-picked columns, never rows, so account ids and device ids
--     cannot ride along;
--   * a bad, expired and revoked token are indistinguishable - all three return
--     null, so probing learns nothing about which events exist;
--   * nobody can UPDATE a share row. Revoking goes through a function, so the
--     history of links is append-then-revoke rather than editable.
--
-- Verified by the new cases in supabase/tests/rls.local.sql and rls.test.mjs.

create table if not exists public.event_shares (
  id            uuid primary key,
  tournament_id uuid not null references public.tournaments (id) on delete cascade,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  -- sha256 hex of the token. The token itself is never stored, anywhere.
  token_hash    text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  -- One legal value today. Phase 2c adds 'writer' as a check change, not a new table.
  role          text not null default 'viewer' check (role in ('viewer')),
  label         text check (char_length(label) <= 60),
  expires_at    timestamptz,
  revoked_at    timestamptz,
  created_at    timestamptz not null default now()
);

create index if not exists event_shares_lookup_idx on public.event_shares (token_hash);
create index if not exists event_shares_event_idx on public.event_shares (tournament_id, created_at);

alter table public.event_shares enable row level security;

revoke all on public.event_shares from anon;
-- The owner can see and delete their own links. No INSERT policy and no UPDATE
-- policy on purpose: creating and revoking go through the functions below, which is
-- what stops a client forging a hash or rewriting a share's history.
grant select, delete on public.event_shares to authenticated;
-- ...and the same at the privilege level, not only in policy. Supabase's default
-- privileges grant ALL on a new table to `authenticated`, so without this an UPDATE
-- reaches the policy layer and is stopped only by the absence of a policy. The local
-- suite reported "0 refused at privilege level" until these two lines existed - the
-- same gap event_log had in 0002.
revoke insert, update, truncate on public.event_shares from authenticated;

create policy "event shares: owner reads own" on public.event_shares
  for select to authenticated using (owner_user_id = (select auth.uid()));
create policy "event shares: owner deletes own" on public.event_shares
  for delete to authenticated using (owner_user_id = (select auth.uid()));

-- ───────────────────────── create a link ─────────────────────────

create or replace function public.create_event_share(
  p_tournament_id uuid,
  p_token text,
  p_expires_at timestamptz default null,
  p_label text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid      uuid := auth.uid();
  share_id uuid := gen_random_uuid();
begin
  if uid is null then
    raise exception 'create_event_share: not authenticated';
  end if;
  -- A short token is a guessable token. 43 base64url characters is 256 bits.
  if p_token is null or char_length(p_token) < 32 then
    raise exception 'create_event_share: token too short';
  end if;
  -- Ownership is checked here, not trusted from the caller.
  if not exists (
    select 1 from public.tournaments t
    where t.id = p_tournament_id and t.user_id = uid and t.deleted_at is null
  ) then
    raise exception 'create_event_share: not your event';
  end if;

  insert into public.event_shares (id, tournament_id, owner_user_id, token_hash, expires_at, label)
  values (
    share_id,
    p_tournament_id,
    uid,
    encode(sha256(convert_to(p_token, 'UTF8')), 'hex'),
    p_expires_at,
    left(p_label, 60)
  );
  return share_id;
end;
$$;

-- ───────────────────────── revoke a link ─────────────────────────

create or replace function public.revoke_event_share(p_share_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'revoke_event_share: not authenticated';
  end if;
  -- Idempotent, and silent about shares that are not yours: a caller learns nothing
  -- about links they do not own.
  update public.event_shares
     set revoked_at = now()
   where id = p_share_id and owner_user_id = uid and revoked_at is null;
end;
$$;

-- ───────────────────── list an event's links ─────────────────────
-- Never returns the hash. There is nothing a client can do with it except attack it
-- offline.

create or replace function public.list_event_shares(p_tournament_id uuid)
returns table (
  id uuid,
  created_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  label text
)
language sql
security definer
set search_path = ''
as $$
  select s.id, s.created_at, s.expires_at, s.revoked_at, s.label
    from public.event_shares s
    join public.tournaments t on t.id = s.tournament_id
   where s.tournament_id = p_tournament_id
     and t.user_id = auth.uid()
     and s.owner_user_id = auth.uid()
   order by s.created_at desc;
$$;

-- ─────────────────── the whole anonymous surface ───────────────────
-- Hand-picked columns, never rows. Adding a column to a table must never widen what
-- a spectator can see, which is why this is a list and not `select *`.

create or replace function public.get_shared_event(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  hashed text;
  ev     public.tournaments;
  result jsonb;
begin
  if p_token is null or char_length(p_token) < 32 then
    return null;
  end if;
  hashed := encode(sha256(convert_to(p_token, 'UTF8')), 'hex');

  select t.* into ev
    from public.event_shares s
    join public.tournaments t on t.id = s.tournament_id
   where s.token_hash = hashed
     and s.revoked_at is null
     and (s.expires_at is null or s.expires_at > now())
     and t.deleted_at is null
   limit 1;

  -- Not found, revoked and expired all land here, indistinguishably.
  if ev.id is null then
    return null;
  end if;

  select jsonb_build_object(
    'event', jsonb_build_object(
      'name',   ev.name,
      'format', ev.format,
      'entryMode', ev.entry_mode,
      'teamSize', ev.team_size,
      'status', ev.status,
      'championTeamId', ev.champion_team_id,
      'createdAt', ev.created_at,
      'config', ev.config,
      'players', ev.players,
      'teams', ev.teams
    ),
    'matches', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', m.client_id,
        'bracket', m.bracket,
        'round', m.round,
        'pool', m.pool,
        'a', m.slot_a,
        'b', m.slot_b,
        'teamA', m.team_a,
        'teamB', m.team_b,
        'scoreA', m.score_a,
        'scoreB', m.score_b,
        'winner', m.winner,
        'court', m.court,
        'label', m.label,
        'completedAt', m.completed_at
      ) order by m.round, m.court nulls last)
      from public.tournament_matches m
      where m.tournament_id = ev.id and m.deleted_at is null
    ), '[]'::jsonb),
    'log', coalesce((
      select jsonb_agg(jsonb_build_object(
        'at', l.at,
        'kind', l.kind,
        'text', l.text
      ) order by l.at)
      from public.event_log l
      where l.tournament_id = ev.id
    ), '[]'::jsonb),
    'fetchedAt', to_jsonb(now())
  ) into result;

  return result;
end;
$$;

-- ───────────────────────────── grants ─────────────────────────────

revoke all on function public.create_event_share(uuid, text, timestamptz, text) from public, anon;
revoke all on function public.revoke_event_share(uuid) from public, anon;
revoke all on function public.list_event_shares(uuid) from public, anon;
revoke all on function public.get_shared_event(text) from public;

grant execute on function public.create_event_share(uuid, text, timestamptz, text) to authenticated;
grant execute on function public.revoke_event_share(uuid) to authenticated;
grant execute on function public.list_event_shares(uuid) to authenticated;
-- The one thing an unauthenticated visitor may call, authorised by the token alone.
grant execute on function public.get_shared_event(text) to anon, authenticated;

comment on function public.get_shared_event(text) is
  'The entire anonymous read surface. Hand-picked columns only: no user ids, no client ids, no emails. Bad, expired and revoked tokens are indistinguishable.';

-- ==========================================================================
-- 0005_event_members.sql
-- ==========================================================================

-- 0005_event_members.sql — phase 2c: invited co-organisers who can enter results.
--
-- This migration contains a BEHAVIOUR CHANGE, not just new objects, so read the first
-- section before changing anything here.
--
-- In 0001, `tournament_matches.user_id` meant "the account that owns this row", and a
-- trigger forced it to auth.uid() on insert AND update. That was correct while only an
-- owner could write. It becomes wrong the moment a helper writes: their update would
-- silently re-stamp the row as theirs, and the row would leave the owner's event.
--
-- So `user_id` now means "the account that owns the EVENT", derived from the parent,
-- and a new `updated_by` column records who wrote last. `event_log.actor_user_id`
-- keeps meaning the ACTOR - that is the entire point of an audit trail.
--
-- Invites reuse `event_shares` (2b) with role = 'writer', rather than a second table
-- with the same shape and a second set of policies to get wrong. Two rules keep the
-- roles from blurring:
--   * `get_shared_event` accepts ONLY a 'viewer' token - a writer invite is not a view
--     link, and grants nothing until an account accepts it;
--   * accepting creates a row in `event_members`, so revoking an invite stops new
--     people joining while removing a member stops that person writing. Different
--     actions, both needed.

-- ───────────────── ownership means the EVENT's owner ─────────────────

alter table public.tournament_matches
  add column if not exists updated_by uuid references auth.users (id) on delete set null;

create or replace function public.force_event_owner()
returns trigger
language plpgsql
security definer   -- reads the parent event, which the writer may not select directly
set search_path = ''
as $$
declare
  owner uuid;
begin
  select t.user_id into owner from public.tournaments t where t.id = new.tournament_id;
  if owner is null then
    raise exception 'force_event_owner: no such event';
  end if;
  -- The row belongs to the event, whoever is holding the pen.
  new.user_id := owner;
  new.updated_by := auth.uid();
  return new;
end;
$$;

comment on function public.force_event_owner() is
  'tournament_matches.user_id is the EVENT owner, not the writer. A helper''s update must not move the row out of the owner''s event (phase 2c).';

drop trigger if exists tournament_matches_owner on public.tournament_matches;
create trigger tournament_matches_owner
  before insert or update on public.tournament_matches
  for each row execute function public.force_event_owner();

-- ─────────────────────────── membership ───────────────────────────

create table if not exists public.event_members (
  tournament_id uuid not null references public.tournaments (id) on delete cascade,
  user_id       uuid not null references auth.users (id) on delete cascade,
  role          text not null default 'writer' check (role in ('writer')),
  invited_by    uuid not null references auth.users (id) on delete cascade,
  created_at    timestamptz not null default now(),
  primary key (tournament_id, user_id)
);

create index if not exists event_members_user_idx on public.event_members (user_id);

alter table public.event_members enable row level security;
revoke all on public.event_members from anon;
-- Read only, and only about yourself or your own events. Joining and removing go
-- through functions, so a client cannot grant itself write access to an event.
grant select on public.event_members to authenticated;
revoke insert, update, delete, truncate on public.event_members from authenticated;

create policy "event members: see your own membership" on public.event_members
  for select to authenticated using (user_id = (select auth.uid()));
create policy "event members: owner sees their event's members" on public.event_members
  for select to authenticated using (
    exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
  );

-- A writer invite is a share row with a different role.
alter table public.event_shares drop constraint if exists event_shares_role_check;
alter table public.event_shares
  add constraint event_shares_role_check check (role in ('viewer', 'writer'));

-- ─────────────── policies: a writer may score, not reshape ───────────────
-- Helper kept SECURITY DEFINER because a writer cannot select the parent event row
-- through their own privileges until the tournaments policy below is in place, and a
-- policy that depends on a policy is how recursion bugs start.

create or replace function public.is_event_writer(p_tournament_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.event_members m
    where m.tournament_id = p_tournament_id
      and m.user_id = auth.uid()
      and m.role = 'writer'
  );
$$;

revoke all on function public.is_event_writer(uuid) from public, anon;
grant execute on function public.is_event_writer(uuid) to authenticated;

-- The event header: a writer READS it (they need the draw to render) and never writes
-- it. Rename, format, re-draw and delete stay with the owner.
drop policy if exists "tournaments: read own" on public.tournaments;
create policy "tournaments: read own or invited" on public.tournaments
  for select to authenticated using (
    user_id = (select auth.uid()) or public.is_event_writer(id)
  );

-- Matches: a writer may read and UPDATE (enter or correct a score). Insert and delete
-- stay with the owner - the schedule is the engine's output, and a helper who could
-- insert rows could invent matches no format produced.
drop policy if exists "event matches: read own" on public.tournament_matches;
create policy "event matches: read own or invited" on public.tournament_matches
  for select to authenticated using (
    user_id = (select auth.uid()) or public.is_event_writer(tournament_id)
  );

drop policy if exists "event matches: update own" on public.tournament_matches;
create policy "event matches: update own or invited" on public.tournament_matches
  for update to authenticated using (
    user_id = (select auth.uid()) or public.is_event_writer(tournament_id)
  ) with check (
    user_id = (select auth.uid()) or public.is_event_writer(tournament_id)
  );

-- The audit trail: a writer appends AS THEMSELVES, which is the point. Still no update
-- and no delete policy, for anyone.
drop policy if exists "event log: read own events" on public.event_log;
create policy "event log: read own or invited events" on public.event_log
  for select to authenticated using (
    exists (
      select 1 from public.tournaments t
      where t.id = tournament_id and t.user_id = (select auth.uid())
    )
    or public.is_event_writer(tournament_id)
  );

drop policy if exists "event log: append to own events" on public.event_log;
create policy "event log: append to own or invited events" on public.event_log
  for insert to authenticated with check (
    actor_user_id = (select auth.uid())
    and (
      exists (
        select 1 from public.tournaments t
        where t.id = tournament_id and t.user_id = (select auth.uid())
      )
      or public.is_event_writer(tournament_id)
    )
  );

-- ──────────────────── create an invite ────────────────────
-- `create_event_share` gains a role, defaulting to 'viewer' so every 2b caller is
-- untouched.

create or replace function public.create_event_share(
  p_tournament_id uuid,
  p_token text,
  p_expires_at timestamptz default null,
  p_label text default null,
  p_role text default 'viewer'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid      uuid := auth.uid();
  share_id uuid := gen_random_uuid();
begin
  if uid is null then
    raise exception 'create_event_share: not authenticated';
  end if;
  if p_token is null or char_length(p_token) < 32 then
    raise exception 'create_event_share: token too short';
  end if;
  if p_role not in ('viewer', 'writer') then
    raise exception 'create_event_share: unknown role';
  end if;
  -- Only the OWNER invites. A writer cannot bring more writers.
  if not exists (
    select 1 from public.tournaments t
    where t.id = p_tournament_id and t.user_id = uid and t.deleted_at is null
  ) then
    raise exception 'create_event_share: not your event';
  end if;

  insert into public.event_shares (id, tournament_id, owner_user_id, token_hash, expires_at, label, role)
  values (
    share_id, p_tournament_id, uid,
    encode(sha256(convert_to(p_token, 'UTF8')), 'hex'),
    p_expires_at, left(p_label, 60), p_role
  );
  return share_id;
end;
$$;

-- ──────────────────── accept an invite ────────────────────
-- Idempotent, and deliberately accepts the same link from several people: a desk
-- running eight courts sends one link to three helpers, and access is still per
-- account and removable per account.

create or replace function public.accept_event_invite(p_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid   uuid := auth.uid();
  s     public.event_shares;
begin
  if uid is null then
    raise exception 'accept_event_invite: not authenticated';
  end if;
  if p_token is null or char_length(p_token) < 32 then
    raise exception 'accept_event_invite: invalid invite';
  end if;

  select * into s
    from public.event_shares
   where token_hash = encode(sha256(convert_to(p_token, 'UTF8')), 'hex')
     and role = 'writer'            -- a VIEWER link is not an invite
     and revoked_at is null
     and (expires_at is null or expires_at > now())
   limit 1;

  -- Unknown, expired, revoked and "that is a view link" are one message on purpose.
  if s.id is null then
    raise exception 'accept_event_invite: invalid invite';
  end if;

  -- The owner accepting their own invite is a no-op, not an error.
  if exists (select 1 from public.tournaments t where t.id = s.tournament_id and t.user_id = uid) then
    return s.tournament_id;
  end if;

  insert into public.event_members (tournament_id, user_id, role, invited_by)
  values (s.tournament_id, uid, 'writer', s.owner_user_id)
  on conflict (tournament_id, user_id) do nothing;

  return s.tournament_id;
end;
$$;

-- ──────────────────── manage the helpers ────────────────────

create or replace function public.list_event_members(p_tournament_id uuid)
returns table (user_id uuid, display_name text, email text, role text, created_at timestamptz)
language sql
security definer
set search_path = ''
as $$
  select m.user_id,
         p.display_name,
         -- The owner invited these people, so the owner may see who accepted. Nobody
         -- else can call this: the join below is the authorisation.
         u.email::text,
         m.role,
         m.created_at
    from public.event_members m
    join public.tournaments t on t.id = m.tournament_id
    left join public.profiles p on p.id = m.user_id
    left join auth.users u on u.id = m.user_id
   where m.tournament_id = p_tournament_id
     and t.user_id = auth.uid()
   order by m.created_at;
$$;

create or replace function public.remove_event_member(p_tournament_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'remove_event_member: not authenticated';
  end if;
  -- Owner only, and silent about events that are not theirs.
  delete from public.event_members m
   where m.tournament_id = p_tournament_id
     and m.user_id = p_user_id
     and exists (
       select 1 from public.tournaments t
       where t.id = p_tournament_id and t.user_id = uid
     );
  -- Their log lines stay. Removing a person is not rewriting history.
end;
$$;

create or replace function public.leave_event(p_tournament_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'leave_event: not authenticated';
  end if;
  delete from public.event_members
   where tournament_id = p_tournament_id and user_id = auth.uid();
end;
$$;

-- ─────────── a viewer link stays a viewer link ───────────
-- Re-created so a 'writer' invite cannot be used as a read link. Identical to 0004
-- except for the role condition.

create or replace function public.get_shared_event(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  hashed text;
  ev     public.tournaments;
  result jsonb;
begin
  if p_token is null or char_length(p_token) < 32 then
    return null;
  end if;
  hashed := encode(sha256(convert_to(p_token, 'UTF8')), 'hex');

  select t.* into ev
    from public.event_shares s
    join public.tournaments t on t.id = s.tournament_id
   where s.token_hash = hashed
     and s.role = 'viewer'          -- phase 2c: an invite is not a view link
     and s.revoked_at is null
     and (s.expires_at is null or s.expires_at > now())
     and t.deleted_at is null
   limit 1;

  if ev.id is null then
    return null;
  end if;

  select jsonb_build_object(
    'event', jsonb_build_object(
      'name',   ev.name,
      'format', ev.format,
      'entryMode', ev.entry_mode,
      'teamSize', ev.team_size,
      'status', ev.status,
      'championTeamId', ev.champion_team_id,
      'createdAt', ev.created_at,
      'config', ev.config,
      'players', ev.players,
      'teams', ev.teams
    ),
    'matches', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', m.client_id,
        'bracket', m.bracket,
        'round', m.round,
        'pool', m.pool,
        'a', m.slot_a,
        'b', m.slot_b,
        'teamA', m.team_a,
        'teamB', m.team_b,
        'scoreA', m.score_a,
        'scoreB', m.score_b,
        'winner', m.winner,
        'court', m.court,
        'label', m.label,
        'completedAt', m.completed_at
      ) order by m.round, m.court nulls last)
      from public.tournament_matches m
      where m.tournament_id = ev.id and m.deleted_at is null
    ), '[]'::jsonb),
    'log', coalesce((
      select jsonb_agg(jsonb_build_object(
        'at', l.at,
        'kind', l.kind,
        'text', l.text
      ) order by l.at)
      from public.event_log l
      where l.tournament_id = ev.id
    ), '[]'::jsonb),
    'fetchedAt', to_jsonb(now())
  ) into result;

  return result;
end;
$$;

-- ───────────────────────────── grants ─────────────────────────────

revoke all on function public.create_event_share(uuid, text, timestamptz, text, text) from public, anon;
revoke all on function public.accept_event_invite(text) from public, anon;
revoke all on function public.list_event_members(uuid) from public, anon;
revoke all on function public.remove_event_member(uuid, uuid) from public, anon;
revoke all on function public.leave_event(uuid) from public, anon;

grant execute on function public.create_event_share(uuid, text, timestamptz, text, text) to authenticated;
grant execute on function public.accept_event_invite(text) to authenticated;
grant execute on function public.list_event_members(uuid) to authenticated;
grant execute on function public.remove_event_member(uuid, uuid) to authenticated;
grant execute on function public.leave_event(uuid) to authenticated;

-- 0004's four-argument version is superseded; dropping it keeps one code path.
drop function if exists public.create_event_share(uuid, text, timestamptz, text);
