import type { MetadataRoute } from "next";

const SITE_URL = "https://pb-card-deck.vercel.app";

// Backlog F483 - robots.txt generated by Next.
//
// `/shared` is disallowed: it is a spectator view of somebody's club night, with real
// player names in it. A crawler could not open one anyway (the token lives in the URL
// fragment, which is never sent to a server), but "not indexable" should not depend on
// that detail holding for ever.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: { userAgent: "*", allow: "/", disallow: ["/api/", "/shared"] },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
