#!/usr/bin/env python3
"""Rebuild supabase/ALL-IN-ONE.sql from the numbered migrations.

The combined file exists only to make setting up a fresh project one paste in the SQL
editor. It is GENERATED, never hand-edited, so it cannot drift from the migrations it
concatenates - which is the whole reason this script exists rather than someone pasting
five files together once.

    python3 scripts/build-combined-migration.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIG = os.path.join(ROOT, "supabase", "migrations")
OUT = os.path.join(ROOT, "supabase", "ALL-IN-ONE.sql")

files = sorted(f for f in os.listdir(MIG) if f.endswith(".sql"))
if not files:
    raise SystemExit("no migrations found in supabase/migrations")

header = [
    "-- ALL-IN-ONE.sql - every migration, in order, for a BRAND-NEW project.",
    "--",
    "-- GENERATED by scripts/build-combined-migration.py. Do not edit this file: edit the",
    "-- migration it came from and regenerate, or the two drift apart.",
    "--",
    "-- Use it when setting a project up by hand: Dashboard -> SQL Editor -> paste -> Run,",
    "-- once. It is NOT idempotent (`create policy` fails if the policy already exists), so",
    "-- on a project that has already had some of these applied, run the individual files",
    "-- and skip the ones that are done.",
    "--",
    "-- Files included, in this order:",
]
header += ["--   * " + f for f in files]

chunks = ["\n".join(header) + "\n"]
bar = "-- " + "=" * 74
for name in files:
    chunks.append("\n" + bar + "\n-- " + name + "\n" + bar + "\n\n")
    with open(os.path.join(MIG, name), encoding="utf-8") as fh:
        chunks.append(fh.read().rstrip() + "\n")

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("".join(chunks))

print("wrote %s from %d migrations" % (os.path.relpath(OUT, ROOT), len(files)))
